server {
  listen 80;
  server_name justinmanion.com www.justinmanion.com;

  return 301 https://$host$request_uri;
}

server {
  listen 443 ssl;
  server_name justinmanion.com www.justinmanion.com;

  ssl_certificate /etc/nginx/certs/fullchain.pem;
  ssl_certificate_key /etc/nginx/certs/privkey.pem;

  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri $uri/ /index.html;
  }

  location = /index.html {
    add_header Cache-Control "no-store, no-cache, must-revalidate";
  }

  location /assets/ {
    add_header Cache-Control "public, max-age=31536000, immutable";
  }
}