server {
  listen 80;

  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri $uri/ /index.html;
  }

  # never cache the HTML entrypoint
  location = /index.html {
    add_header Cache-Control "no-store, no-cache, must-revalidate";
  }

  # aggressively cache hashed assets
  location /assets/ {
    add_header Cache-Control "public, max-age=31536000, immutable";
  }
}